accounts:
  - name: alice
    coins: ["20000mand", "200000000cred"]
  - name: bob
    coins: ["10000mand", "100000000cred"]
  - name: faucet
    coins: ["1000000000000mand", "100000000cred"]
validator:
  name: bob
  staked: 2000000cred
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: faucet
  coins: ["50000000mand", "1000000cred"]
  coins_max: ["10000mand", "100cred"]
genesis:
  chain_id: "test"
  app_state:
    staking:
      params:
        bond_denom: "cred"
