// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vote/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the vote module's genesis state.
type GenesisState struct {
	Params         Params       `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	VoteLogList    []VoteLog    `protobuf:"bytes,2,rep,name=voteLogList,proto3" json:"voteLogList"`
	VoteLogCount   uint64       `protobuf:"varint,3,opt,name=voteLogCount,proto3" json:"voteLogCount,omitempty"`
	VoteCastedList []VoteCasted `protobuf:"bytes,4,rep,name=voteCastedList,proto3" json:"voteCastedList"`
	BallotList     []Ballot     `protobuf:"bytes,5,rep,name=ballotList,proto3" json:"ballotList"`
	BookList       []Book       `protobuf:"bytes,6,rep,name=bookList,proto3" json:"bookList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f60978020b4166a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetVoteLogList() []VoteLog {
	if m != nil {
		return m.VoteLogList
	}
	return nil
}

func (m *GenesisState) GetVoteLogCount() uint64 {
	if m != nil {
		return m.VoteLogCount
	}
	return 0
}

func (m *GenesisState) GetVoteCastedList() []VoteCasted {
	if m != nil {
		return m.VoteCastedList
	}
	return nil
}

func (m *GenesisState) GetBallotList() []Ballot {
	if m != nil {
		return m.BallotList
	}
	return nil
}

func (m *GenesisState) GetBookList() []Book {
	if m != nil {
		return m.BookList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "mandelabs.mande.vote.GenesisState")
}

func init() { proto.RegisterFile("vote/genesis.proto", fileDescriptor_9f60978020b4166a) }

var fileDescriptor_9f60978020b4166a = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0x02, 0x41,
	0x18, 0xc6, 0x77, 0xd3, 0x24, 0x46, 0x29, 0x9a, 0x24, 0x64, 0xa9, 0x6d, 0xf1, 0xb4, 0x97, 0x66,
	0xc1, 0x6e, 0xd1, 0x69, 0x25, 0xba, 0x48, 0x84, 0x41, 0x87, 0x2e, 0x31, 0xab, 0xc3, 0x24, 0xae,
	0xbe, 0xe2, 0x8c, 0x51, 0x9f, 0xa0, 0x6b, 0x1f, 0xcb, 0xa3, 0xc7, 0x4e, 0x11, 0xfa, 0x45, 0x62,
	0xde, 0x19, 0x4a, 0xc3, 0xbd, 0x2c, 0xef, 0x3c, 0xfb, 0x3c, 0xbf, 0x67, 0xfe, 0x10, 0xfa, 0x02,
	0x5a, 0x24, 0x52, 0x8c, 0x85, 0x1a, 0x28, 0x36, 0x99, 0x82, 0x06, 0x5a, 0x1f, 0xf1, 0x71, 0x5f,
	0xe4, 0x3c, 0x53, 0x0c, 0x27, 0x66, 0x3c, 0x41, 0x5d, 0x82, 0x04, 0x34, 0x24, 0x66, 0xb2, 0xde,
	0xe0, 0x10, 0xf3, 0x13, 0x3e, 0xe5, 0x23, 0x17, 0x0f, 0x8e, 0x50, 0x32, 0x9f, 0xa7, 0x1c, 0xa4,
	0x13, 0x8f, 0xff, 0xc4, 0x1e, 0x57, 0x5a, 0xf4, 0x37, 0xf2, 0x19, 0xcf, 0x73, 0xd0, 0x4e, 0x3a,
	0xb0, 0x12, 0xc0, 0xd0, 0x0a, 0xcd, 0xf7, 0x12, 0xa9, 0xdd, 0xd8, 0x1d, 0xde, 0x6b, 0xae, 0x05,
	0xbd, 0x24, 0x15, 0xdb, 0xd8, 0xf0, 0x23, 0x3f, 0xae, 0xb6, 0x4e, 0xd8, 0xb6, 0x1d, 0xb3, 0x3b,
	0xf4, 0xa4, 0xe5, 0xf9, 0xd7, 0x99, 0xd7, 0x75, 0x09, 0x7a, 0x4d, 0xaa, 0xe6, 0x67, 0x07, 0x64,
	0x67, 0xa0, 0x74, 0x63, 0x27, 0x2a, 0xc5, 0xd5, 0xd6, 0xe9, 0x76, 0xc0, 0x83, 0x35, 0x3a, 0xc2,
	0x7a, 0x8e, 0x36, 0x49, 0xcd, 0x2d, 0xdb, 0x30, 0x1b, 0xeb, 0x46, 0x29, 0xf2, 0xe3, 0x72, 0x77,
	0x43, 0xa3, 0xb7, 0x64, 0xdf, 0xac, 0xdb, 0x78, 0x5e, 0x6c, 0x2b, 0x63, 0x5b, 0x54, 0xdc, 0x66,
	0xbd, 0xae, 0xf0, 0x5f, 0x9a, 0xa6, 0x84, 0xd8, 0x8b, 0x42, 0xd6, 0x2e, 0xb2, 0x0a, 0x8e, 0x9e,
	0xa2, 0xcf, 0x71, 0xd6, 0x52, 0xf4, 0x8a, 0xec, 0x99, 0x9b, 0x45, 0x42, 0x05, 0x09, 0x41, 0x01,
	0x01, 0x60, 0xe8, 0xf2, 0xbf, 0x89, 0x34, 0x9d, 0x2f, 0x43, 0x7f, 0xb1, 0x0c, 0xfd, 0xef, 0x65,
	0xe8, 0x7f, 0xac, 0x42, 0x6f, 0xb1, 0x0a, 0xbd, 0xcf, 0x55, 0xe8, 0x3d, 0xc6, 0x72, 0xa0, 0x9f,
	0x67, 0x19, 0xeb, 0xc1, 0x28, 0x41, 0xca, 0xb9, 0x01, 0xda, 0x31, 0x79, 0xc5, 0x87, 0x4f, 0xf4,
	0xdb, 0x44, 0xa8, 0xac, 0x82, 0x8f, 0x7a, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff, 0xee, 0xc0, 0xbd,
	0xc8, 0x7a, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BookList) > 0 {
		for iNdEx := len(m.BookList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BookList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.BallotList) > 0 {
		for iNdEx := len(m.BallotList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BallotList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.VoteCastedList) > 0 {
		for iNdEx := len(m.VoteCastedList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VoteCastedList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.VoteLogCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.VoteLogCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.VoteLogList) > 0 {
		for iNdEx := len(m.VoteLogList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VoteLogList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.VoteLogList) > 0 {
		for _, e := range m.VoteLogList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.VoteLogCount != 0 {
		n += 1 + sovGenesis(uint64(m.VoteLogCount))
	}
	if len(m.VoteCastedList) > 0 {
		for _, e := range m.VoteCastedList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BallotList) > 0 {
		for _, e := range m.BallotList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BookList) > 0 {
		for _, e := range m.BookList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteLogList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteLogList = append(m.VoteLogList, VoteLog{})
			if err := m.VoteLogList[len(m.VoteLogList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteLogCount", wireType)
			}
			m.VoteLogCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteLogCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteCastedList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteCastedList = append(m.VoteCastedList, VoteCasted{})
			if err := m.VoteCastedList[len(m.VoteCastedList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BallotList = append(m.BallotList, Ballot{})
			if err := m.BallotList[len(m.BallotList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BookList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BookList = append(m.BookList, Book{})
			if err := m.BookList[len(m.BookList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
